INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (1, 'Clean Code', 'Martin, Robert', 'Education', 1);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (2, 'A Brief History Of Time', 'Hawking, Stephen', 'Science Fiction', 0);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (3, 'Moby Dick', 'Melvill, German', 'Fiction', null);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (4, 'Thinking In Java', 'Eckel, Bruce', 'Education', 5);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (5, 'Guns, Germs, and Steel', 'Diamond, Jared', 'Science Fiction', 0);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (6, 'Effective Java', 'Bloch, Joshua', 'Education', 5);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (7, 'Spring In Action', 'Walls, Craig', 'Education', null);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (8, 'A Scanner Darkly', 'Dick, Philip', 'Fiction', null);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (9, 'Refactoring', 'Fowler, Martin', 'Education', 5);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (10, 'Salambo', 'Flaubert, Gustav', 'Fiction', null);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (11, 'The Discovery of Modern Science', 'Weinberg, Steven', 'Science Fiction', null);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (12, 'OCA Study Guide', 'Selikoff, Scott', 'Education', null);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (13, 'Java Persistence With Hibernate', 'King, Gavin', 'Education', 5);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (14, 'Contact', 'Sagan, Carl', 'Science Fiction', null);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (15, 'Atomic Scala', 'Eckel, Bruce', 'Education', null);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (16, 'Crime And Punishment', 'Dostoyevsky, Fiodor', 'Fiction', 4);
INSERT INTO librarydb.book (id, title, author, type, student_id) VALUES (18, 'The Art of C++', 'Schildt, Herbert', 'Education', null);